version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - html:/usr/share/nginx/html
      - ./test:/usr/share/nginx/test
    networks:
      - backend