nginx:
  image: nginx:alpine
  container_name: web
  volumes:
    - html:/usr/share/nginx/html

mysql:
  image: mysql:5.7
  container_name: db
  volumes:
    - db_data:/var/lib/mysql
  environment:
    - key: MYSQL_ROOT_PASSWORD
      value: rootpassword
    - key: MYSQL_DATABASE
      value: testdb
    - key: MYSQL_USER
      value: user
    - key: MYSQL_PASSWORD
      value: password

redis:
  enable: true
  image: redis:alpine
  container_name: redis

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  environment:
    - key: PMA_HOST
      value: db
    - key: MYSQL_ROOT_PASSWORD
      value: rootpassword