version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    {{- template "phpmyadmin-env" .}} 
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - backend