name: Integration Tests

on:
  pull_request:
    branches:
      - develop
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  build-and-test:
    if: contains(github.event.head_commit.message, '[integration-tests]')
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20' # Specify your Go version

      # Build the Go application
      - name: Build Go application
        run: |
          go build -o dcpm

      # Move the binary to the integrations_tests directory
      - name: Move binary to integration_tests directory
        run: mv dcpm integration_tests/

      # Install Docker
      - name: Install Docker
        uses: docker/setup-buildx-action@v2

      # Run pytest tests
      - name: Run pytest integration tests
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install pytest docker
          cd integration_tests
          pytest .
