name: Integration Tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get commit message
        id: get_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
          echo "COMMIT_MESSAGE=${COMMIT_MESSAGE}" >> $GITHUB_ENV

      - name: Check for [integration-tests] in commit message
        id: check_commit_message
        run: |
          if [[ "${{ env.COMMIT_MESSAGE }}" == *"[integration-tests]"* ]]; then
            echo "Run integration tests"
            echo "RUN_INTEGRATION_TESTS=true" >> $GITHUB_ENV
          else
            echo "Skip integration tests"
            echo "RUN_INTEGRATION_TESTS=false" >> $GITHUB_ENV
          fi

      - name: Set up Python
        if: env.RUN_INTEGRATION_TESTS == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the Python version you need

      - name: Create virtual environment and install dependencies
        if: env.RUN_INTEGRATION_TESTS == 'true'
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install pytest

      - name: Build Go application
        if: env.RUN_INTEGRATION_TESTS == 'true'
        run: |
          go build -o dcpm ./path/to/your/main/package

      - name: Move binary to integration_tests directory
        if: env.RUN_INTEGRATION_TESTS == 'true'
        run: |
          mkdir -p integrations_tests
          mv dcpm integrations_tests/

      - name: Install Docker
        if: env.RUN_INTEGRATION_TESTS == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Install Docker Compose
        if: env.RUN_INTEGRATION_TESTS == 'true'
        run: |
          VERSION=$(curl --silent "https://api.github.com/repos/docker/compose/releases/latest" | jq -r '.tag_name')
          sudo curl -L "https://github.com/docker/compose/releases/download/${VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Run integration tests
        if: env.RUN_INTEGRATION_TESTS == 'true'
        run: |
          cd integrations_tests
          pytest tests/
