name: Main

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # Install Go module dependencies
      - name: Install dependencies
        run: go mod tidy

      # Run Go unit tests
      - name: Run unit tests
        run: go test ./src -v
