name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.6'

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install semantic-release and plugins
        run: |
          npm install semantic-release @semantic-release/git @semantic-release/exec @semantic-release/changelog @semantic-release/release-notes-generator @semantic-release/npm @semantic-release/github

      - name: Build Go binary
        run: |
          go build -o dcpm

      - name: Create zip archive
        run: |
          zip -r docker-compose-package-manager.zip . -x "."

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Upload Release Assets
        uses: actions/upload-artifact@v3
        with:
          name: myproject.zip
          path: myproject.zip

      - name: Upload Binary Asset
        uses: actions/upload-artifact@v3
        with:
          name: dcpm
          path: dcpm
